import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {SiteHeader} from "@/components/custom/site-header";
import {SiteFooter} from "@/components/custom/site-footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
          <html lang="en" suppressHydrationWarning>
          <head />
          <body>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
              <div className="flex flex-col min-h-screen">
                  <SiteHeader />
                  <div className="flex-grow">
                      {children}
                  </div>
                  <SiteFooter />
              </div>
          </ThemeProvider>
          </body>
          </html>
      </>
  );
}
